name: Publish to npm

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org'

    - name: Get version from tag
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    
    - name: Install dependencies
        run: npm install

    - name: Run npm test
        run: npm test

    - name: Update version in package.json
      run: npm version --allow-same-version --no-git-tag-version ${{ steps.get_version.outputs.VERSION }}

    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
